### ISSUE TITLE
Remove text-shadow from heading 

### ISSUE THREAD

**Issue by Thecarisma** [Thecarisma/themata#4]
```css
.bodywrapper h1,
.bodywrapper h2,
.bodywrapper h3,
.bodywrapper h4,
.bodywrapper h5,
.bodywrapper h6 {
    text-shadow: 0px 0px 0 white !important;
}
```
